version: "3"
services:
    web:
        build: .
        image: apoblock/arp:latest
        ports:
            - "8000:80"
            - "2222:2222"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
